### ISSUE TITLE
Request to update most up-to-date version of the Data Source Support Matrix

### ISSUE THREAD

**Issue by raju-aravind** [NetAppDocs/oncommand-insight#28]
### Page URL

https://docs.netapp.com/us-en/oncommand-insight/config-admin/data-source-support-information.html

### Page title

Data source support information

### Summary

Hello Team, 

As per our document repository & support site, the pdf linked below is the most up-to-date version of the Data Source Support Matrix.

(The most current version of the document can be found at the [NetApp Support Site](https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf). .

However this document looks not to be the latest because page 135 indicates the support for Clustered data ONTAP only till 9.11.1. Hence we request to review and update the OnCommand Insight Data Source Support Matrix document anywhere applicable.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-alavoie** [comment]
I have created an internal tracking ticket for this. My understanding is that the Support Matrix has not changed significantly since OCI 7.3.14 (enough to warrant a new release) , but I have noted the specific request in the ticket and will follow-up her to learn whether we expect the next update.

**Comment by raju-aravind** [comment]
@netapp-alavoie Is there any update on the internal ticket to make required changes to support matrix?

**Comment by netapp-alavoie** [comment]
@raju-aravind Hello.  We are looking into moving the OCI Support Matrix to the same format as the one for Cloud Insights that you reference. At that time I believe the matrix will be updated as well.  The Acquisition team are the ones who build the matrix, so my involvement in it only happens when they provide something to be published.  If I have more information around this that I can share, I'll inform this ticket.

-Tony

**Comment by raju-aravind** [comment]
@netapp-alavoie Thank you for the update. While we wait for the OCI support Matrix to be completely changed. 
1. can we consider cloud Insights support matrix as the latest for OCI as well?
2. If not, can you confirm which vSphere versions are supported by OCI 7.3.15?

**Comment by netapp-alavoie** [comment]
Hi @raju-aravind , 

In general, the Collector Support Matrix (whether for OCI or for Cloud Insights) tries to list configurations which are known to work, but is not intended to show all configurations that *can* work. With that in mind, any newer version of a supported device's firmware, control software, etc., is likely to be functional, unless otherwise specifically noted. So for your eample, while my acquisition person didn't have exact versions off the top of their head, they say any fairly modern vSphere should be fine. We've supported it long enough to have a good range backward and if there's a problem with some new release the acquisition team would likely consider it a bug to fix whether it's officially in the matrix or not.

I hope this helps.

-Tony

**Comment by raju-aravind** [comment]
@netapp-alavoie Is there update/progress from the acquisition team on the internal ticket? 
From our previous conversation i understand that acquisition team is planning to update the matrix, do we have an ETA on when this will be updated? 
We would like to share the supported version with customers with correct information rather than customers reporting a problem and then fix from our end.

**Comment by netapp-alavoie** [comment]
The Data Source Support Matrix is now included on the OCi documentation site, and is up-to-date.
https://docs.netapp.com/us-en/oncommand-insight/config-admin/reference_data_collector_support_matrix.html
